### ISSUE TITLE
`cannot coerce a set to a string` in kexec-bundle format

### ISSUE THREAD

**Issue by maxeaubrey** [nix-community/nixos-generators#142]
Ran into this trying to set up a system the other day. Reverting to before this commit fixed the issue for me https://github.com/nix-community/nixos-generators/commit/85014f358b3bc0c29ac50487235f62251e0d0471

```
$ nixos-generate -o result -f kexec-bundle -c config.nix 
error: cannot coerce a set to a string

       at /nix/store/8m7rykjwdwxyhhkixcl6agcwj5kng2lf-nixos-generators/share/nixos-generator/formats/kexec.nix:43:9:

           42|         ${kexec_tarball_self_extract_script} \
           43|         ${kexec_tarball}/tarball/nixos-system-${kexec_tarball.system}.tar.xz \
             |         ^
           44|         > $out
(use '--show-trace' to show detailed location information)
```

For context, this was on a fresh nix install in an OCI compute instance. `config.nix` just had openssh enabled.

**Comment by Lassulus** [comment]
I opened up a PR which should fix that. would be nice if you could test if it fixes your usecase :)

**Comment by 4825764518** [comment]
> I opened up a PR which should fix that. would be nice if you could test if it fixes your usecase :)

#143 does not fix this, I encountered the same issue trying to build a kexec in the hetzner rescue system today. Reverting to  the commit specified by OP resulting in normal functionality.

**Comment by Lassulus** [comment]
weird, did you try the checked out version or the version which is shipped in nixpkgs?

**Comment by Lassulus** [comment]
ah indeed its another time on the same line :D not sure why that worked for me before though

**Comment by Lassulus** [comment]
ok, should be fixed in https://github.com/nix-community/nixos-generators/commit/117ed432a4e0b17651b53f1af143baa42aa1f84f
