### ISSUE TITLE
Building images completely Broken?

### ISSUE THREAD

**Issue by philon123** [nix-community/nixos-generators#183]
Executing this command:
`nix run github:nix-community/nixos-generators -- -c ./iso/configuration.nix -f install-iso --show-trace`

First prints a deprecation warning and then fails with following error:

 ```
error: The option 'filename' does not exist. Definition values:
       - In '/nix/store/p1i3mkr916aqhp2g4s87yg0fiipiydsy-nixos-generate/share/nixos-generator/formats/install-iso.nix': "*.iso"

       … while evaluating the attribute 'config'

       at /nix/store/pvah1vlkwpyrizidj55myzd8r0460fz6-mihiym1pvr3p2nkk8l8iijbab6j1zf63-source/lib/modules.nix:236:9:

          235|         options = checked options;
          236|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          237|         _module = checked (config._module);
```

It was working fine before (last tested probably 2 months ago). The error happens even when removing all contents of config file `./iso/configuration.nix` so all that's left in there is `{}`. I've also tried using format `iso` with same error (just referencing `../formats/ist.nix`). 

I'm a Nix noob so please be gentle :) But help would be greatly appreciated.

**Comment by Lassulus** [comment]
ah, thanks, maybe the PR I merged wasn't ready. I will investigate :)

**Comment by Lassulus** [comment]
please try again!

**Comment by philon123** [comment]
hm still the same. Do I need to update my local version of nixos-generators so it will get the newest version?

**Comment by Lassulus** [comment]
uh probably, usually it should upgrade automatically but maybe there is some caching included, maybe there is a way for nix-run to force a invalidation?

**Comment by philon123** [comment]
I just ran `nix flake lock github:nix-community/nixos-generators` and after that my command is working again! Output is scrolling.. Thanks so much for the fast support @Lassulus it's really appreciated. This can be closed.

**Comment by blaggacao** [comment]
@philon123 Can you test out the following PR?

https://github.com/nix-community/nixos-generators/pull/184

`nix run github:nix-community/nixos-generators?rev=e2f624e7c5a292bf4e04b34d628afa0a29a587a3 -- -c ./iso/configuration.nix -f install-iso --show-trace`

**Comment by hurricanehrndz** [comment]
@blaggacao pr #184 seems to work

**Comment by hurricanehrndz** [comment]
@Lassulus and @blaggacao without referencing the draft PR here is the results
```
hurricane in 🌐 Lucy in nixos-config on  main [!] via ❄️  impure
❯ nix run github:nix-community/nixos-generators --no-use-registries -- \
  --format install-iso \
  --flake '.#bootstrap'
warning: Git tree '/home/hurricane/src/nixos-config' is dirty
warning: Git tree '/home/hurricane/src/nixos-config' is dirty
error: The option `filename' does not exist. Definition values:
       - In `/nix/store/5ndhx5acps1rrw1jgj4153xysi1v0vqx-nixos-generate/share/nixos-generator/formats/install-iso.nix': "*.iso"

hurricane in 🌐 Lucy in nixos-config on  main [!] via ❄️  impure
❯ nix run github:nix-community/nixos-generators -- \
  --format install-iso \
  --flake '.#bootstrap'
warning: Git tree '/home/hurricane/src/nixos-config' is dirty
warning: Git tree '/home/hurricane/src/nixos-config' is dirty
error: The option `filename' does not exist. Definition values:
       - In `/nix/store/5ndhx5acps1rrw1jgj4153xysi1v0vqx-nixos-generate/share/nixos-generator/formats/install-iso.nix': "*.iso"

```
